/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaCriptSimetrica.java
 *
 * Created on 09/12/2011, 22:25:40
 */
package guiopenssl.gui;

import java.io.BufferedReader;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import utilites.Shell;

/**
 *
 * @author gabriel
 */
public class TelaCriptAssimetrica extends javax.swing.JFrame {

    /** Creates new form TelaCriptSimetrica */
    public TelaCriptAssimetrica() {
        initComponents();
    }

    public boolean ValidarForm() {
        
        Long numero;

        if (campoNumBits.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o número de bits da chave!", "Alerta", JOptionPane.ERROR_MESSAGE);
            caminhoArquivoOrigem.grabFocus();
            return false;
        }
        
        try {
            numero = Long.parseLong(campoNumBits.getText());

            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "Digite um número válido maior que zero!", "Alerta", JOptionPane.ERROR_MESSAGE);
                campoNumBits.grabFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite um número!", "Alerta", JOptionPane.ERROR_MESSAGE);
            campoNumBits.grabFocus();
            return false;
        }
        
        if (caminhoArquivoOrigem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o caminho do Arquivo!", "Alerta", JOptionPane.ERROR_MESSAGE);
            caminhoArquivoOrigem.grabFocus();
            return false;
        }
        
        if (caminhoArquivoDestino.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o arquivo Destino!", "Alerta", JOptionPane.ERROR_MESSAGE);
            caminhoArquivoDestino.grabFocus();
            return false;
        }
        
        if ((campoSenha.getPassword().length == 0) && !jLerChaveArquivo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Digite um senha para a criptografia!", "Alerta", JOptionPane.ERROR_MESSAGE);
            campoSenha.grabFocus();
            return false;
        }
        
        if (campoSenha.getText().compareTo(campoConfSenha.getText()) != 0) {
            JOptionPane.showMessageDialog(null, "Senhas não conferem!", "Alerta", JOptionPane.ERROR_MESSAGE);
            campoSenha.grabFocus();
            campoConfSenha.grabFocus();
            return false;
        }
        
        if (jLerChaveArquivo.isSelected()) {
            if (caminhoLerChaveArquivo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Escolha o arquivo com a senha! (A senha deve estar na primeira linha do arquivo.)", "Alerta", JOptionPane.ERROR_MESSAGE);
                caminhoLerChaveArquivo.grabFocus();
                return false;
            }
        }
        return true;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoAlgoritmo = new javax.swing.JLabel();
        tipoAlgoritmo = new javax.swing.JComboBox();
        labelArquivoOrigem = new javax.swing.JLabel();
        selecionarArquivoOrigem = new javax.swing.JButton();
        caminhoArquivoOrigem = new javax.swing.JTextField();
        labelArquivoDestino = new javax.swing.JLabel();
        caminhoArquivoDestino = new javax.swing.JTextField();
        selecionarArquivoDestino = new javax.swing.JButton();
        labelSenha = new javax.swing.JLabel();
        labelConfSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoConfSenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLerChaveArquivo = new javax.swing.JCheckBox();
        caminhoLerChaveArquivo = new javax.swing.JTextField();
        botaoLerChaveArquivo = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoCriptografar = new javax.swing.JButton();
        labelNumBits = new javax.swing.JLabel();
        campoNumBits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criptografia Assimétrica");

        labelTipoAlgoritmo.setText("Selecione o tipo de algoritmo:");

        tipoAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diffie-Hellman", "RSA", "DSA (Digital Assignature Algorithm)" }));
        tipoAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAlgoritmoActionPerformed(evt);
            }
        });

        labelArquivoOrigem.setText("Selecione o arquivo de origem:");

        selecionarArquivoOrigem.setText("selecionar");
        selecionarArquivoOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoOrigemActionPerformed(evt);
            }
        });

        caminhoArquivoOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoArquivoOrigemActionPerformed(evt);
            }
        });

        labelArquivoDestino.setText("Crie o arquivo de destino no diretório desejado:");

        caminhoArquivoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoArquivoDestinoActionPerformed(evt);
            }
        });

        selecionarArquivoDestino.setText("selecionar");
        selecionarArquivoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoDestinoActionPerformed(evt);
            }
        });

        labelSenha.setText("Digite senha:");

        labelConfSenha.setText("Confirme senha:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLerChaveArquivo.setText("Ler Chave de Arquivo");
        jLerChaveArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLerChaveArquivoActionPerformed(evt);
            }
        });

        botaoLerChaveArquivo.setText("selecionar");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoCriptografar.setText("Criptografar!");
        botaoCriptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriptografarActionPerformed(evt);
            }
        });

        labelNumBits.setText("Selecione o número de bits:");

        campoNumBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumBitsActionPerformed(evt);
            }
        });
        campoNumBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNumBitsKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipoAlgoritmo)
                            .addComponent(labelNumBits))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNumBits, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(tipoAlgoritmo, 0, 318, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelArquivoDestino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(caminhoArquivoDestino))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelArquivoOrigem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(caminhoArquivoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(selecionarArquivoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selecionarArquivoOrigem)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelConfSenha)
                                .addComponent(labelSenha))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoSenha)
                                .addComponent(campoConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(caminhoLerChaveArquivo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botaoLerChaveArquivo))
                                .addComponent(jLerChaveArquivo)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCriptografar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoCancelar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoAlgoritmo)
                    .addComponent(tipoAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumBits)
                    .addComponent(campoNumBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArquivoOrigem)
                    .addComponent(caminhoArquivoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarArquivoOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArquivoDestino)
                    .addComponent(caminhoArquivoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarArquivoDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelConfSenha)
                            .addComponent(campoConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLerChaveArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caminhoLerChaveArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoLerChaveArquivo)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoCriptografar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tipoAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlgoritmoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tipoAlgoritmoActionPerformed

private void caminhoArquivoOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoArquivoOrigemActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_caminhoArquivoOrigemActionPerformed

private void caminhoArquivoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoArquivoDestinoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_caminhoArquivoDestinoActionPerformed

private void selecionarArquivoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoDestinoActionPerformed
// TODO add your handling code here:
    JFileChooser abrir = new JFileChooser();
    String caminho;
    int retorno = abrir.showDialog(null, "Salvar");

    if (retorno == JFileChooser.APPROVE_OPTION) {
        caminho = abrir.getSelectedFile().getAbsolutePath();
        caminhoArquivoDestino.setText(caminho);
    }
}//GEN-LAST:event_selecionarArquivoDestinoActionPerformed

private void jLerChaveArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLerChaveArquivoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jLerChaveArquivoActionPerformed

private void selecionarArquivoOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoOrigemActionPerformed
// TODO add your handling code here:
    JFileChooser abrir = new JFileChooser();
    String caminho;
    int retorno = abrir.showOpenDialog(null);

    if (retorno == JFileChooser.APPROVE_OPTION) {
        caminho = abrir.getSelectedFile().getAbsolutePath();
        caminhoArquivoOrigem.setText(caminho);
    }
}//GEN-LAST:event_selecionarArquivoOrigemActionPerformed

private void botaoCriptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriptografarActionPerformed
// TODO add your handling code here:
    Shell s = new Shell();
    BufferedReader buf;
    String shell = "openssl ";

    if (ValidarForm()) {
        String caminhoOrigem = caminhoArquivoOrigem.getText();
        String caminhoDestino = caminhoArquivoDestino.getText();
        String caminhoArqSenha;
        File fCriptografa = new File(caminhoOrigem);
        File fDestino = new File(caminhoDestino);


        switch (tipoAlgoritmo.getSelectedIndex()) {
            case 0:
                shell = shell + "";
                break;
            case 1:
                shell = shell + "";
                break;
        }
    }
}//GEN-LAST:event_botaoCriptografarActionPerformed

private void campoNumBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumBitsActionPerformed
// TODO add your handling code here:   
}//GEN-LAST:event_campoNumBitsActionPerformed

private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_botaoCancelarActionPerformed

private void campoNumBitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumBitsKeyTyped
// TODO add your handling code here:
}//GEN-LAST:event_campoNumBitsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriptAssimetrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriptAssimetrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriptAssimetrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriptAssimetrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaCriptAssimetrica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoCriptografar;
    private javax.swing.JButton botaoLerChaveArquivo;
    private javax.swing.JTextField caminhoArquivoDestino;
    private javax.swing.JTextField caminhoArquivoOrigem;
    private javax.swing.JTextField caminhoLerChaveArquivo;
    private javax.swing.JPasswordField campoConfSenha;
    private javax.swing.JTextField campoNumBits;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JCheckBox jLerChaveArquivo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelArquivoDestino;
    private javax.swing.JLabel labelArquivoOrigem;
    private javax.swing.JLabel labelConfSenha;
    private javax.swing.JLabel labelNumBits;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTipoAlgoritmo;
    private javax.swing.JButton selecionarArquivoDestino;
    private javax.swing.JButton selecionarArquivoOrigem;
    private javax.swing.JComboBox tipoAlgoritmo;
    // End of variables declaration//GEN-END:variables
}
