/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frontend.java
 *
 * Created on 04/12/2011, 16:24:20
 */
package guiopenssl.gui;

import guiopenssl.gui.*;

/**
 *
 * @author Edviges
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form Frontend */
    public TelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuCriptografia = new javax.swing.JMenu();
        itemCriptoSimetrica = new javax.swing.JMenuItem();
        menuCriptoAssimetrica = new javax.swing.JMenu();
        itemMenuAssimCripto = new javax.swing.JMenuItem();
        menuCertificados = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenSSL");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiopenssl/icon.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setAutoscrolls(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        menuArquivo.setText("Arquivo");
        jMenuBar2.add(menuArquivo);

        menuCriptografia.setText("Criptografia");

        itemCriptoSimetrica.setText("Simétrica");
        itemCriptoSimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCriptoSimetricaActionPerformed(evt);
            }
        });
        menuCriptografia.add(itemCriptoSimetrica);

        menuCriptoAssimetrica.setText("Assimétrica");

        itemMenuAssimCripto.setText("Criptografar");
        itemMenuAssimCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAssimCriptoActionPerformed(evt);
            }
        });
        menuCriptoAssimetrica.add(itemMenuAssimCripto);

        menuCriptografia.add(menuCriptoAssimetrica);

        jMenuBar2.add(menuCriptografia);

        menuCertificados.setText("Certificados");

        jMenu7.setText("Assinaturas Digitais");

        jMenuItem6.setText("Verificar assinatura de certificados digitais");
        jMenu7.add(jMenuItem6);

        jMenuItem9.setText("Gerar assinaturas digitais em arquivos");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Verificar assinaturas digitais em arquivos");
        jMenu7.add(jMenuItem10);

        menuCertificados.add(jMenu7);

        jMenu8.setText("Certificados Digitais");

        jMenuItem5.setText("Assinar certificados digitais");
        jMenu8.add(jMenuItem5);

        jMenuItem8.setText("Exibir informações de certificado");
        jMenu8.add(jMenuItem8);

        jMenuItem4.setText("Gerar certificados digitais");
        jMenu8.add(jMenuItem4);

        jMenuItem7.setText("Gerar requisição de certificado");
        jMenu8.add(jMenuItem7);

        menuCertificados.add(jMenu8);

        jMenuItem3.setText("Gerar autoridade certificadora (CA)");
        menuCertificados.add(jMenuItem3);

        jMenuBar2.add(menuCertificados);

        menuAjuda.setText("Ajuda");

        jMenuItem1.setText("Exibir Ajuda");
        menuAjuda.add(jMenuItem1);

        jMenuItem2.setText("Sobre o Projeto");
        menuAjuda.add(jMenuItem2);

        jMenuItem15.setText("Sair");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair(evt);
            }
        });
        menuAjuda.add(jMenuItem15);

        jMenuBar2.add(menuAjuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair
// TODO add your handling code here:
        setVisible(false);
        dispose();
}//GEN-LAST:event_Sair

private void itemCriptoSimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCriptoSimetricaActionPerformed
// TODO add your handling code here:
    TelaCriptSimetrica telaCriptSimetrica = new TelaCriptSimetrica();
        telaCriptSimetrica.setVisible(true);
}//GEN-LAST:event_itemCriptoSimetricaActionPerformed

private void itemMenuAssimCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAssimCriptoActionPerformed
// TODO add your handling code here:
    TelaCriptAssimetrica telaCriptAssimetrica = new TelaCriptAssimetrica();
    telaCriptAssimetrica.setVisible(true);
}//GEN-LAST:event_itemMenuAssimCriptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCriptoSimetrica;
    private javax.swing.JMenuItem itemMenuAssimCripto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCertificados;
    private javax.swing.JMenu menuCriptoAssimetrica;
    private javax.swing.JMenu menuCriptografia;
    // End of variables declaration//GEN-END:variables
}
