/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaCriarChavePrivadaDialog.java
 *
 * Created on 15/12/2011, 00:27:18
 */
package guiopenssl.gui;

import javax.swing.JFileChooser;

/**
 *
 * @author gabriel
 */
public class TelaCriarChavePrivadaDialog extends javax.swing.JDialog {
    private String caminho;

    /** Creates new form TelaCriarChavePrivadaDialog */
    public TelaCriarChavePrivadaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public String getCaminho(){
        return caminho;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoConfSenha = new javax.swing.JPasswordField();
        campoNumBits = new javax.swing.JTextField();
        selecionarArquivoDestinoChaveprivada = new javax.swing.JButton();
        labelNumBits = new javax.swing.JLabel();
        labelConfSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        labelUsoSenha = new javax.swing.JLabel();
        checkSenha = new javax.swing.JCheckBox();
        labelSenha = new javax.swing.JLabel();
        botaoCriaChavePrivada = new javax.swing.JButton();
        labelArquivoDestinoChavePrivada = new javax.swing.JLabel();
        caminhoArquivoDestinoChavePrivada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        campoConfSenha.setEnabled(false);

        campoNumBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumBitsActionPerformed(evt);
            }
        });
        campoNumBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNumBitsKeyTyped(evt);
            }
        });

        selecionarArquivoDestinoChaveprivada.setText("selecionar");
        selecionarArquivoDestinoChaveprivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoDestinoChaveprivadaActionPerformed(evt);
            }
        });

        labelNumBits.setText("Selecione o número de bits:");

        labelConfSenha.setText("Confirme senha:");

        campoSenha.setEnabled(false);

        labelUsoSenha.setText("Desejar usar senha?");

        checkSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSenhaActionPerformed(evt);
            }
        });

        labelSenha.setText("Digite senha:");

        botaoCriaChavePrivada.setText("Criar Chave Privada!");
        botaoCriaChavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriaChavePrivadaActionPerformed(evt);
            }
        });

        labelArquivoDestinoChavePrivada.setText("Crie a chave no local de destino:");

        caminhoArquivoDestinoChavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoArquivoDestinoChavePrivadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha)
                            .addComponent(labelConfSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoSenha)
                            .addComponent(campoConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCriaChavePrivada))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelArquivoDestinoChavePrivada)
                            .addComponent(labelNumBits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNumBits, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caminhoArquivoDestinoChavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecionarArquivoDestinoChaveprivada))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsoSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkSenha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumBits)
                    .addComponent(campoNumBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionarArquivoDestinoChaveprivada)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelArquivoDestinoChavePrivada)
                        .addComponent(caminhoArquivoDestinoChavePrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsoSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfSenha)
                    .addComponent(botaoCriaChavePrivada))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void campoNumBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumBitsActionPerformed
// TODO add your handling code here: 
}//GEN-LAST:event_campoNumBitsActionPerformed

private void campoNumBitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumBitsKeyTyped
// TODO add your handling code here:
}//GEN-LAST:event_campoNumBitsKeyTyped

private void selecionarArquivoDestinoChaveprivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoDestinoChaveprivadaActionPerformed
// TODO add your handling code here:
    JFileChooser abrir = new JFileChooser();
    String caminho;
    int retorno = abrir.showDialog(null, "Salvar");

    if (retorno == JFileChooser.APPROVE_OPTION) {
        caminho = abrir.getSelectedFile().getAbsolutePath();
        caminhoArquivoDestinoChavePrivada.setText(caminho);
    }
}//GEN-LAST:event_selecionarArquivoDestinoChaveprivadaActionPerformed

private void checkSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSenhaActionPerformed
// TODO add your handling code here:
    if(checkSenha.isSelected()){
        campoSenha.setEnabled(true);
        campoConfSenha.setEnabled(true);
        campoSenha.grabFocus();
    }else{
        campoSenha.setEnabled(false);
        campoConfSenha.setEnabled(false);
    }
}//GEN-LAST:event_checkSenhaActionPerformed

private void botaoCriaChavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriaChavePrivadaActionPerformed
// TODO add your handling code here:
    
 //Quando você gerar a chave você vai saber o caminho então guarda em caminho e depois dá um getCaminho e pronto.   
    
}//GEN-LAST:event_botaoCriaChavePrivadaActionPerformed

private void caminhoArquivoDestinoChavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoArquivoDestinoChavePrivadaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_caminhoArquivoDestinoChavePrivadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarChavePrivadaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarChavePrivadaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarChavePrivadaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarChavePrivadaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaCriarChavePrivadaDialog dialog = new TelaCriarChavePrivadaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriaChavePrivada;
    private javax.swing.JTextField caminhoArquivoDestinoChavePrivada;
    private javax.swing.JPasswordField campoConfSenha;
    private javax.swing.JTextField campoNumBits;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JCheckBox checkSenha;
    private javax.swing.JLabel labelArquivoDestinoChavePrivada;
    private javax.swing.JLabel labelConfSenha;
    private javax.swing.JLabel labelNumBits;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsoSenha;
    private javax.swing.JButton selecionarArquivoDestinoChaveprivada;
    // End of variables declaration//GEN-END:variables
}
