/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaCriptSimetrica.java
 *
 * Created on 09/12/2011, 22:25:40
 */
package guiopenssl.gui;

import guiopenssl.utilities.Shell;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import guiopenssl.utilities.Shell;

/**
 *
 * @author gabriel
 */
public class TelaCA extends javax.swing.JFrame {

    /** Creates new form TelaCriptSimetrica */
    public TelaCA() {
        initComponents();
    }

    public void/*Boolean*/ ValidarForm() {
        
        /*if ((senhaCA.getPassword().length == 0)) {
            JOptionPane.showMessageDialog(null, "Digite um senha!", "Alerta", JOptionPane.ERROR_MESSAGE);
            senhaCA.grabFocus();
            return false;
        }

        if (senhaCA.getText().compareTo(senhaCA1.getText()) != 0) {
            JOptionPane.showMessageDialog(null, "Senhas não conferem!", "Alerta", JOptionPane.ERROR_MESSAGE);
            senhaCA1.grabFocus();
            return false;
        }
               
        return true;*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criptografia Assimétrica");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para criar uma CA (autoridade cerificadora), siga os passos a seguir:\n\n1. Entre no terminal e digite: cd /usr/lib/ssl/ e dê Enter.\n2. Modifique o arquivo openssl.cnf, em modo de super usuário, digitando: sudo\n     <vim | gedit | mcedit> openssl.cnf e digite sua senha.\n3. Modifique como listado abaixo nas seguintes linhas:\n     linha 75: default_md = sha256 (ou sha384 ou sha512, o que preferir)\n     linha 106: default_bits = 2048 (ou 4096)\n     linha 129: countryName_default = BR\n     linha 133: stateOrProvincyName_default = PB\n     linha 137: localityName_default = Joao Pessoa (essa linha você vai criar)\n     linha 140: 0.organizationName_default = UFPB\n     linha 147: organizationalUnitName_default = Departamento de Informatica (essa linha aparece \n     comentada, você vai retirar a cerquilha do início)\n     linha 151: commonName_default = Autoridade Certificadora da UFPB (essa linha você vai criar)\n     linha 155: emailAddress_default = albuquerque.brunna@gmail.com\n4. OK, dê um esc e digite :wq. Dê enter para salvar o documento.\n5. Agora vá para o dietório misc: cd misc/ e dê Enter. Abra o documento CA.pl.\n6.  ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaCA().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
