/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaHashAssinaArquivo.java
 *
 * Created on 15/12/2011, 02:29:22
 */
package guiopenssl.gui;

import guiopenssl.utilities.Shell;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaHashAssinaArquivo extends javax.swing.JFrame {

    /** Creates new form TelaHashAssinaArquivo */
    public TelaHashAssinaArquivo() {
        initComponents();
    }
    
    public Boolean ValidarForm(){
        
        if(caminhoArquivoCriptografa.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Escolha o caminho do Arquivo!", "Alerta" , JOptionPane.ERROR_MESSAGE);
                caminhoArquivoCriptografa.grabFocus();
                return false;
        }
        if(caminhoArquivoCriptografa1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Escolha o caminho do Arquivo!", "Alerta" , JOptionPane.ERROR_MESSAGE);
                caminhoArquivoCriptografa1.grabFocus();
                return false;
        }
        
        
        
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caminhoArquivoCriptografa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboAlgoritmo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        caminhoArquivoCriptografa1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selecione Arquivo a ser Assinado:");
        jLabel1.setToolTipText("");

        jButton2.setText("selecionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o algoritmo de hash: ");

        comboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "md4", "md5", "ripemd160", "sha", "sha1", "sha224", "sha256", "sha384", "sha512", "whirlpool" }));

        jButton1.setText("Assinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione Arquivo com Chave privada:");
        jLabel3.setToolTipText("");

        jButton3.setText("selecionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caminhoArquivoCriptografa, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(comboAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caminhoArquivoCriptografa1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(caminhoArquivoCriptografa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3)
                    .addComponent(caminhoArquivoCriptografa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    JFileChooser abrir = new JFileChooser();
    String caminho;
    int retorno = abrir.showOpenDialog(null);  
    
    if (retorno==JFileChooser.APPROVE_OPTION){  
        caminho = abrir.getSelectedFile().getAbsolutePath();
        caminhoArquivoCriptografa.setText(caminho);
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    Shell s = new Shell();
    BufferedReader bufer = null;
    String line = null;
    String shell = "openssl dgst ";
    
    if(ValidarForm()){
        String caminhoDestino = caminhoArquivoCriptografa.getText();
        File fDestino = new File(caminhoDestino);
        
        switch(comboAlgoritmo.getSelectedIndex()){
            case 0:
                shell = shell + "-md4 ";
                break;
            case 1:
                shell = shell + "-md5 ";
                break;
            case 2:
                shell = shell + "-ripemd160 ";
                break;
            case 3:
                shell = shell + "-sha ";
                break;
            case 4:
                shell = shell + "-sha1 ";
                break;
            case 5:
                shell = shell + "-sha224 ";
                break;
            case 6:
                shell = shell + "-sha256 ";
                break;
            case 7:
                shell = shell + "-sha384 ";
                break;
            case 8:
                shell = shell + "-sha512 ";
                break;
            case 9:
                shell = shell + "-whirlpool ";
                break;
        }
        
        shell = shell + "-sign " + caminhoArquivoCriptografa1.getText() + " ";
        
        shell = shell +"-out "+ caminhoArquivoCriptografa.getText();
        
        s.ExecComandoShell(shell);
        
       /* try {
            bufer = s.GetBufferedReader();
        } catch (Exception ex) {
            Logger.getLogger(TelaHash.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaHash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*try {
            line = bufer.readLine();
        } catch (IOException ex) {
            Logger.getLogger(TelaHash.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        JOptionPane.showMessageDialog(null, "Arquivo Assinado com Sucesso! " + fDestino.getName() ,"OK" , JOptionPane.INFORMATION_MESSAGE);
        
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    JFileChooser abrir = new JFileChooser();
    String caminho;
    int retorno = abrir.showOpenDialog(null);  
    
    if (retorno==JFileChooser.APPROVE_OPTION){  
        caminho = abrir.getSelectedFile().getAbsolutePath();
        caminhoArquivoCriptografa1.setText(caminho);
    }
}//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHashAssinaArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHashAssinaArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHashAssinaArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHashAssinaArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaHashAssinaArquivo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caminhoArquivoCriptografa;
    private javax.swing.JTextField caminhoArquivoCriptografa1;
    private javax.swing.JComboBox comboAlgoritmo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
